"""Добавлена Enum Модель в таблицу users в поле active

Revision ID: 7a3faf0818f2
Revises: e562bfefbf0a
Create Date: 2025-09-29 18:40:15.746251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3faf0818f2'
down_revision: Union[str, Sequence[str], None] = 'e562bfefbf0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
