"""улучшение токенов

Revision ID: 9df6cbb38a1f
Revises: e5cdf724307c
Create Date: 2025-09-30 03:41:30.079213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df6cbb38a1f'
down_revision: Union[str, Sequence[str], None] = 'e5cdf724307c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tokens', 'is_revoked')
    # ### end Alembic commands ###
