"""улучшение токенов

Revision ID: e5cdf724307c
Revises: 7a3faf0818f2
Create Date: 2025-09-30 03:30:55.706013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5cdf724307c'
down_revision: Union[str, Sequence[str], None] = '7a3faf0818f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'is_revoked')
    op.drop_column('refresh_tokens', 'expires_at')
    # ### end Alembic commands ###
